# https://www.gitpod.io/docs/config-gitpod-file/
image:
  file: .gitpod.Dockerfile

# Run these for the cypress tests:

# export CHROME_VERSION=119.0.6045.199-1
# export FIREFOX_VERSION=120.0

# # sudo apt-get update
# sudo apt-get install -y \
#     libgtk2.0-0 \
#     libgtk-3-0
# sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq \
#     libgbm-dev \
#     libnotify-dev
# sudo apt-get install -y \
#     libgconf-2-4 \
#     libnss3 \
#     libxss1
# sudo apt-get install -y \
#     libasound2 \
#     libxtst6 \
#     xauth \
#     libu2f-udev \
#     xvfb

# sudo wget -O /usr/src/google-chrome-stable_current_amd64.deb "http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb"
# sudo dpkg -i /usr/src/google-chrome-stable_current_amd64.deb

# sudo apt-get install -f -y && \
#     sudo rm -f /usr/src/google-chrome-stable_current_amd64.deb

# google-chrome --version
# sudo apt-get install mplayer -y
# sudo wget --no-verbose -O /tmp/firefox.tar.bz2 https://download-installer.cdn.mozilla.net/pub/firefox/releases/$FIREFOX_VERSION/linux-x86_64/en-US/firefox-$FIREFOX_VERSION.tar.bz2
# sudo tar -C /opt -xjf /tmp/firefox.tar.bz2 \
#     && sudo rm /tmp/firefox.tar.bz2 \
#     && sudo ln -fs /opt/firefox/firefox /usr/bin/firefox
#     echo  " node version:    $(node -v) \n" \
#     "npm version:     $(npm -v) \n" \
#     "yarn version:    $(yarn -v) \n" \
#     "debian version:  $(cat /etc/debian_version) \n" \
#     "Chrome version:  $(google-chrome --version) \n" \
#     "Firefox version: $(firefox --version) \n" \
#     "git version:     $(git --version) \n" \
#     "whoami:          $(whoami) \n"
tasks:
  - init: npm install && npm run build:production
    command: printf '\n\n 🎉🎉 The plugin is available in the Explorer 🎉🎉\n\nRight-click the .vsix file and click "Install Extension VSIX" to test it.\n\nRun "npm test" to run tests\n'
